import enum

class RoleEnum(str, enum.Enum):
    ADMIN = "ADMIN"
    FACULTY = "FACULTY"
    STUDENT = "STUDENT"

class BloomLevelEnum(str, enum.Enum):
    REMEMBER = "REMEMBER"
    UNDERSTAND = "UNDERSTAND"
    APPLY = "APPLY"
    ANALYZE = "ANALYZE"
    EVALUATE = "EVALUATE"
    CREATE = "CREATE"

class QuestionTypeEnum(str, enum.Enum):
    MCQ = "MCQ"
    TRUE_FALSE = "TRUE_FALSE"
    FILL_BLANK = "FILL_BLANK"
    SHORT_ANSWER = "SHORT_ANSWER"
    DESCRIPTIVE = "DESCRIPTIVE"
    PROBLEM_SOLVING = "PROBLEM_SOLVING"
    NUMERICAL = "NUMERICAL"
    PROGRAMMING = "PROGRAMMING"
    CASE_STUDY = "CASE_STUDY"

class DifficultyLevelEnum(str, enum.Enum):
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"

class QuestionStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    AI_GENERATED = "AI_GENERATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"

class BlueprintStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"

class QuestionPaperStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"

class PaperGenerationMethodEnum(str, enum.Enum):
    MANUAL = "MANUAL"
    AI_GENERATED = "AI_GENERATED"
    HYBRID = "HYBRID"

class AnswerKeyStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"

class ExamStatusEnum(str, enum.Enum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    ONGOING = "ONGOING"
    COMPLETED = "COMPLETED"
    EVALUATION = "EVALUATION"
    RESULT_PUBLISHED = "RESULT_PUBLISHED"
    ARCHIVED = "ARCHIVED"

class AttendanceStatusEnum(str, enum.Enum):
    PRESENT = "PRESENT"
    ABSENT = "ABSENT"
    DEBARRED = "DEBARRED"

class AnswerPaperStatusEnum(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    OCR_COMPLETED = "OCR_COMPLETED"
    EVALUATION_PENDING = "EVALUATION_PENDING"
    EVALUATED = "EVALUATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    FINALIZED = "FINALIZED"
    ERROR = "ERROR"

class ExtractionMethodEnum(str, enum.Enum):
    OCR = "OCR"
    MANUAL = "MANUAL"
    HYBRID = "HYBRID"

class EvaluatorTypeEnum(str, enum.Enum):
    AI = "AI"
    FACULTY = "FACULTY"
    HYBRID = "HYBRID"

class EvaluationStatusEnum(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FINALIZED = "FINALIZED"
    REOPENED = "REOPENED"

class FeedbackTypeEnum(str, enum.Enum):
    CORRECT = "CORRECT"
    MISSING_CONCEPT = "MISSING_CONCEPT"
    IMPROVEMENT = "IMPROVEMENT"
    STRUCTURE = "STRUCTURE"
    CONCEPT_GAP = "CONCEPT_GAP"

class ReviewActionEnum(str, enum.Enum):
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    RE_EVALUATED = "RE_EVALUATED"
    ACCEPT_AI_MARK = "ACCEPT_AI_MARK"
    OVERRIDE_MARK = "OVERRIDE_MARK"
    REQUEST_REEVALUATION = "REQUEST_REEVALUATION"
    APPROVE = "APPROVE"
    FINALIZE = "FINALIZE"
    BULK_ACCEPT = "BULK_ACCEPT"
    REOPEN = "REOPEN"

class FileCategoryEnum(str, enum.Enum):
    SYLLABUS = "SYLLABUS"
    REFERENCE_MATERIAL = "REFERENCE_MATERIAL"
    QUESTION_PAPER = "QUESTION_PAPER"
    ANSWER_PAPER = "ANSWER_PAPER"
    ANSWER_PAGE = "ANSWER_PAGE"
    REPORT = "REPORT"
    OTHER = "OTHER"

class AuditActionEnum(str, enum.Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    PASSWORD_CHANGE = "PASSWORD_CHANGE"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    SYLLABUS_UPLOADED = "SYLLABUS_UPLOADED"
    SYLLABUS_PROCESSED = "SYLLABUS_PROCESSED"
    SYLLABUS_APPROVED = "SYLLABUS_APPROVED"
    SYLLABUS_UPDATED = "SYLLABUS_UPDATED"
    ACADEMIC_STRUCTURE_CREATED = "ACADEMIC_STRUCTURE_CREATED"
    ACADEMIC_STRUCTURE_UPDATED = "ACADEMIC_STRUCTURE_UPDATED"
    QUESTION_CREATED = "QUESTION_CREATED"
    QUESTION_UPDATED = "QUESTION_UPDATED"
    QUESTION_VERSION_CREATED = "QUESTION_VERSION_CREATED"
    QUESTION_APPROVED = "QUESTION_APPROVED"
    QUESTION_REJECTED = "QUESTION_REJECTED"
    QUESTION_ARCHIVED = "QUESTION_ARCHIVED"
    AI_GENERATION_STARTED = "AI_GENERATION_STARTED"
    AI_GENERATION_COMPLETED = "AI_GENERATION_COMPLETED"
    AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
    BLUEPRINT_CREATED = "BLUEPRINT_CREATED"
    BLUEPRINT_UPDATED = "BLUEPRINT_UPDATED"
    BLUEPRINT_VALIDATED = "BLUEPRINT_VALIDATED"
    BLUEPRINT_DELETED = "BLUEPRINT_DELETED"
    PAPER_GENERATION_STARTED = "PAPER_GENERATION_STARTED"
    PAPER_GENERATION_COMPLETED = "PAPER_GENERATION_COMPLETED"
    PAPER_GENERATION_FAILED = "PAPER_GENERATION_FAILED"
    PAPER_VERSION_CREATED = "PAPER_VERSION_CREATED"
    PAPER_QUESTION_REPLACED = "PAPER_QUESTION_REPLACED"
    PAPER_SECTION_REGENERATED = "PAPER_SECTION_REGENERATED"
    PAPER_REGENERATED = "PAPER_REGENERATED"
    PAPER_APPROVED = "PAPER_APPROVED"
    PAPER_ARCHIVED = "PAPER_ARCHIVED"
    GENERATE_QUESTION = "GENERATE_QUESTION"
    GENERATE_PAPER = "GENERATE_PAPER"
    GENERATE_ANSWER_KEY = "GENERATE_ANSWER_KEY"
    UPLOAD_ANSWER_PAPER = "UPLOAD_ANSWER_PAPER"
    QUESTION_BANK_CREATED = "QUESTION_BANK_CREATED"
    RUBRIC_CREATED = "RUBRIC_CREATED"
    RUBRIC_UPDATED = "RUBRIC_UPDATED"
    RUBRIC_ASSIGNED = "RUBRIC_ASSIGNED"
    ANSWER_KEY_CREATED = "ANSWER_KEY_CREATED"
    ANSWER_KEY_UPDATED = "ANSWER_KEY_UPDATED"
    ANSWER_KEY_VERSION_CREATED = "ANSWER_KEY_VERSION_CREATED"
    ANSWER_KEY_APPROVED = "ANSWER_KEY_APPROVED"
    ANSWER_KEY_PUBLISHED = "ANSWER_KEY_PUBLISHED"
    QUESTION_PAPER_APPROVED = "QUESTION_PAPER_APPROVED"
    QUESTION_PAPER_PUBLISHED = "QUESTION_PAPER_PUBLISHED"
    RUN_OCR = "RUN_OCR"
    RUN_EVALUATION = "RUN_EVALUATION"
    FACULTY_OVERRIDE = "FACULTY_OVERRIDE"
    PUBLISH_RESULT = "PUBLISH_RESULT"
    FACULTY_REVIEW_STARTED = "FACULTY_REVIEW_STARTED"
    AI_MARK_ACCEPTED = "AI_MARK_ACCEPTED"
    MARK_OVERRIDDEN = "MARK_OVERRIDDEN"
    REEVALUATION_REQUESTED = "REEVALUATION_REQUESTED"
    EVALUATION_APPROVED = "EVALUATION_APPROVED"
    EVALUATION_FINALIZED = "EVALUATION_FINALIZED"
    EVALUATION_REOPENED = "EVALUATION_REOPENED"
    BULK_AI_MARKS_ACCEPTED = "BULK_AI_MARKS_ACCEPTED"
    SIMILARITY_ANALYSIS_STARTED = "SIMILARITY_ANALYSIS_STARTED"
    SIMILARITY_ANALYSIS_COMPLETED = "SIMILARITY_ANALYSIS_COMPLETED"
    SIMILARITY_REANALYZED = "SIMILARITY_REANALYZED"
    PLAGIARISM_CASE_REVIEWED = "PLAGIARISM_CASE_REVIEWED"
    PLAGIARISM_CASE_DISMISSED = "PLAGIARISM_CASE_DISMISSED"
    ANALYTICS_GENERATED = "ANALYTICS_GENERATED"
    QUESTION_QUALITY_ANALYSIS_STARTED = "QUESTION_QUALITY_ANALYSIS_STARTED"
    QUESTION_QUALITY_ANALYSIS_COMPLETED = "QUESTION_QUALITY_ANALYSIS_COMPLETED"
    QUESTION_QUALITY_REVIEWED = "QUESTION_QUALITY_REVIEWED"
    QUESTION_REUSE_REVIEWED = "QUESTION_REUSE_REVIEWED"
    EXAM_BLUEPRINT_ANALYZED = "EXAM_BLUEPRINT_ANALYZED"



class SyllabusProcessingStatusEnum(str, enum.Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    STRUCTURED = "STRUCTURED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    FAILED = "FAILED"


