from backend.app.schemas.user import (
    UserCreate,
    UserResponse,
    UserUpdate,
    UserProfileUpdate,
    UserStatusUpdate,
    UserRoleUpdate,
    UserListResponse,
    RoleSchema
)
from backend.app.schemas.auth import (
    LoginRequest,
    TokenData,
    AuthResponse,
    RegisterRequest,
    ChangePasswordRequest,
    UserAuthInfo
)
from backend.app.schemas.academic import (
    DepartmentSchema,
    DepartmentCreate,
    DepartmentUpdate,
    CourseSchema,
    CourseCreate,
    CourseUpdate,
    SemesterSchema,
    AcademicYearSchema,
    SubjectSchema,
    SubjectCreate,
    SubjectUpdate,
    UnitSchema,
    UnitCreate,
    UnitUpdate,
    TopicSchema,
    TopicCreate,
    TopicUpdate,
    LearningOutcomeSchema,
    LearningOutcomeCreate,
    LearningOutcomeUpdate,
    FacultySubjectAssignmentResponse,
    FacultySubjectAssignmentCreate,
)
from backend.app.schemas.syllabus import (
    SyllabusStructure,
    SyllabusUnit,
    SyllabusTopic,
    SyllabusLearningOutcome,
    SourceReference,
    SyllabusDocumentResponse,
    SyllabusReviewUpdate,
)
from backend.app.schemas.question import (
    QuestionBase,
    QuestionCreate,
    QuestionUpdate,
    QuestionStatusUpdate,
    QuestionVersionResponse,
    QuestionResponse,
    QuestionListResponse,
    MCQOptionsSchema,
    ValidationDataSchema,
)
from backend.app.schemas.question_generation import (
    QuestionGenerationRequest,
    GeneratedQuestionSchema,
    QuestionValidationResult,
    QuestionGenerationRunResponse,
)
from backend.app.schemas.question_bank import (
    QuestionBankBase,
    QuestionBankCreate,
    QuestionBankUpdate,
    QuestionBankResponse,
    QuestionBankItemResponse,
    AddQuestionsToBankRequest,
)
from backend.app.schemas.blueprint import (
    BlueprintRuleBase,
    BlueprintRuleCreate,
    BlueprintRuleUpdate,
    BlueprintRuleResponse,
    BlueprintBase,
    BlueprintCreate,
    BlueprintUpdate,
    BlueprintResponse,
    BlueprintValidationResult,
)
from backend.app.schemas.question_paper import (
    QuestionPaperItemResponse,
    QuestionPaperVersionResponse,
    QuestionPaperResponse,
    QuestionPaperListResponse,
    PaperGenerationRequest,
    PaperValidationResult,
    QuestionReplacementRequest,
    SectionRegenerateRequest,
    PaperRegenerateRequest,
    PaperStatusUpdateRequest,
)
try:
    from app.schemas.answer_key import (
        AnswerKeyItemBase, AnswerKeyItemCreate, AnswerKeyItemUpdate, AnswerKeyItemResponse,
        AnswerKeyCreate, AnswerKeyUpdate, AnswerKeyResponse, AnswerKeyValidationResult, AIDraftAnswerKeyRequest
    )
    from app.schemas.rubric import (
        RubricCriterionBase, RubricCriterionCreate, RubricCriterionUpdate, RubricCriterionResponse,
        RubricCreate, RubricUpdate, RubricResponse, RubricValidationResult, RubricAssignmentRequest
    )
    from app.schemas.question_paper_review import (
        PaperReviewChecklistResponse, PaperApprovalRequest, PaperPublishRequest
    )
except ImportError:
    from backend.app.schemas.answer_key import (
        AnswerKeyItemBase, AnswerKeyItemCreate, AnswerKeyItemUpdate, AnswerKeyItemResponse,
        AnswerKeyCreate, AnswerKeyUpdate, AnswerKeyResponse, AnswerKeyValidationResult, AIDraftAnswerKeyRequest
    )
    from backend.app.schemas.rubric import (
        RubricCriterionBase, RubricCriterionCreate, RubricCriterionUpdate, RubricCriterionResponse,
        RubricCreate, RubricUpdate, RubricResponse, RubricValidationResult, RubricAssignmentRequest
    )
    from backend.app.schemas.question_paper_review import (
        PaperReviewChecklistResponse, PaperApprovalRequest, PaperPublishRequest
    )

__all__ = [
    "UserCreate",
    "UserResponse",
    "UserUpdate",
    "UserProfileUpdate",
    "UserStatusUpdate",
    "UserRoleUpdate",
    "UserListResponse",
    "RoleSchema",
    "LoginRequest",
    "TokenData",
    "AuthResponse",
    "RegisterRequest",
    "ChangePasswordRequest",
    "UserAuthInfo",
    "DepartmentSchema",
    "DepartmentCreate",
    "DepartmentUpdate",
    "CourseSchema",
    "CourseCreate",
    "CourseUpdate",
    "SemesterSchema",
    "AcademicYearSchema",
    "SubjectSchema",
    "SubjectCreate",
    "SubjectUpdate",
    "UnitSchema",
    "UnitCreate",
    "UnitUpdate",
    "TopicSchema",
    "TopicCreate",
    "TopicUpdate",
    "LearningOutcomeSchema",
    "LearningOutcomeCreate",
    "LearningOutcomeUpdate",
    "FacultySubjectAssignmentResponse",
    "FacultySubjectAssignmentCreate",
    "SyllabusStructure",
    "SyllabusUnit",
    "SyllabusTopic",
    "SyllabusLearningOutcome",
    "SourceReference",
    "SyllabusDocumentResponse",
    "SyllabusReviewUpdate",
    "QuestionBase",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionStatusUpdate",
    "QuestionVersionResponse",
    "QuestionResponse",
    "QuestionListResponse",
    "MCQOptionsSchema",
    "ValidationDataSchema",
    "QuestionGenerationRequest",
    "GeneratedQuestionSchema",
    "QuestionValidationResult",
    "QuestionGenerationRunResponse",
    "QuestionBankBase",
    "QuestionBankCreate",
    "QuestionBankUpdate",
    "QuestionBankResponse",
    "QuestionBankItemResponse",
    "AddQuestionsToBankRequest",
    "BlueprintRuleBase",
    "BlueprintRuleCreate",
    "BlueprintRuleUpdate",
    "BlueprintRuleResponse",
    "BlueprintBase",
    "BlueprintCreate",
    "BlueprintUpdate",
    "BlueprintResponse",
    "BlueprintValidationResult",
    "QuestionPaperItemResponse",
    "QuestionPaperVersionResponse",
    "QuestionPaperResponse",
    "QuestionPaperListResponse",
    "PaperGenerationRequest",
    "PaperValidationResult",
    "QuestionReplacementRequest",
    "SectionRegenerateRequest",
    "PaperRegenerateRequest",
    "PaperStatusUpdateRequest",
    "AnswerKeyItemBase",
    "AnswerKeyItemCreate",
    "AnswerKeyItemUpdate",
    "AnswerKeyItemResponse",
    "AnswerKeyCreate",
    "AnswerKeyUpdate",
    "AnswerKeyResponse",
    "AnswerKeyValidationResult",
    "AIDraftAnswerKeyRequest",
    "RubricCriterionBase",
    "RubricCriterionCreate",
    "RubricCriterionUpdate",
    "RubricCriterionResponse",
    "RubricCreate",
    "RubricUpdate",
    "RubricResponse",
    "RubricValidationResult",
    "RubricAssignmentRequest",
    "PaperReviewChecklistResponse",
    "PaperApprovalRequest",
    "PaperPublishRequest",
]

