"""phase_2_complete_schema

Revision ID: 45d20984c7ea
Revises: 'None'
Create Date: 2026-09-17 20:37:21.204935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
try:
    from app.db.guid import GUID
except ImportError:
    from backend.app.db.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '45d20984c7ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_is_current'), 'academic_years', ['is_current'], unique=False)
    op.create_index(op.f('ix_academic_years_name'), 'academic_years', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'FACULTY', 'STUDENT', name='roleenum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('semesters',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_number'), 'semesters', ['number'], unique=True)
    op.create_table('courses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('department_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('role_id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('department_id', GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_registration_number'), 'users', ['registration_number'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'GENERATE_QUESTION', 'GENERATE_PAPER', 'GENERATE_ANSWER_KEY', 'UPLOAD_ANSWER_PAPER', 'RUN_OCR', 'RUN_EVALUATION', 'FACULTY_OVERRIDE', 'PUBLISH_RESULT', name='auditactionenum'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('file_category', sa.Enum('SYLLABUS', 'REFERENCE_MATERIAL', 'QUESTION_PAPER', 'ANSWER_PAPER', 'ANSWER_PAGE', 'REPORT', 'OTHER', name='filecategoryenum'), nullable=False),
    sa.Column('uploaded_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_assets_file_category'), 'file_assets', ['file_category'], unique=False)
    op.create_table('subjects',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('course_id', GUID(), nullable=False),
    sa.Column('department_id', GUID(), nullable=True),
    sa.Column('semester_id', GUID(), nullable=False),
    sa.Column('academic_year_id', GUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'course_id', name='uq_subject_code_course')
    )
    op.create_index(op.f('ix_subjects_academic_year_id'), 'subjects', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_course_id'), 'subjects', ['course_id'], unique=False)
    op.create_index(op.f('ix_subjects_department_id'), 'subjects', ['department_id'], unique=False)
    op.create_index(op.f('ix_subjects_semester_id'), 'subjects', ['semester_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='blueprintstatusenum'), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_status'), 'blueprints', ['status'], unique=False)
    op.create_index(op.f('ix_blueprints_subject_id'), 'blueprints', ['subject_id'], unique=False)
    op.create_table('learning_outcomes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomlevelenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'code', name='uq_co_subject_code')
    )
    op.create_index(op.f('ix_learning_outcomes_subject_id'), 'learning_outcomes', ['subject_id'], unique=False)
    op.create_table('question_banks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_banks_subject_id'), 'question_banks', ['subject_id'], unique=False)
    op.create_table('units',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'unit_number', name='uq_unit_subject_number')
    )
    op.create_index(op.f('ix_units_subject_id'), 'units', ['subject_id'], unique=False)
    op.create_table('blueprint_rules',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('blueprint_id', GUID(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('marks_per_question', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevelenum'), nullable=True),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomlevelenum'), nullable=True),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'FILL_BLANK', 'SHORT_ANSWER', 'DESCRIPTIVE', 'PROBLEM_SOLVING', 'NUMERICAL', 'PROGRAMMING', 'CASE_STUDY', name='questiontypeenum'), nullable=True),
    sa.Column('minimum_count', sa.Integer(), nullable=True),
    sa.Column('maximum_count', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_rules_blueprint_id'), 'blueprint_rules', ['blueprint_id'], unique=False)
    op.create_table('question_papers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('blueprint_id', GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('paper_code', sa.String(length=50), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='questionpaperstatusenum'), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_papers_blueprint_id'), 'question_papers', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_question_papers_paper_code'), 'question_papers', ['paper_code'], unique=True)
    op.create_index(op.f('ix_question_papers_status'), 'question_papers', ['status'], unique=False)
    op.create_index(op.f('ix_question_papers_subject_id'), 'question_papers', ['subject_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_unit_id'), 'topics', ['unit_id'], unique=False)
    op.create_table('question_paper_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_paper_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('generation_method', sa.Enum('MANUAL', 'AI_GENERATED', 'HYBRID', name='papergenerationmethodenum'), nullable=False),
    sa.Column('generated_by', GUID(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_paper_id', 'version_number', name='uq_paper_version_number')
    )
    op.create_index(op.f('ix_question_paper_versions_question_paper_id'), 'question_paper_versions', ['question_paper_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('unit_id', GUID(), nullable=True),
    sa.Column('topic_id', GUID(), nullable=True),
    sa.Column('learning_outcome_id', GUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'TRUE_FALSE', 'FILL_BLANK', 'SHORT_ANSWER', 'DESCRIPTIVE', 'PROBLEM_SOLVING', 'NUMERICAL', 'PROGRAMMING', 'CASE_STUDY', name='questiontypeenum'), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevelenum'), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomlevelenum'), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'REJECTED', name='questionstatusenum'), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcomes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_bloom_level'), 'questions', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_learning_outcome_id'), 'questions', ['learning_outcome_id'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_questions_unit_id'), 'questions', ['unit_id'], unique=False)
    op.create_table('answer_keys',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_paper_version_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'ARCHIVED', name='answerkeystatusenum'), nullable=False),
    sa.Column('generated_by', GUID(), nullable=True),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_version_id'], ['question_paper_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_paper_version_id', 'version_number', name='uq_answer_key_paper_version')
    )
    op.create_index(op.f('ix_answer_keys_question_paper_version_id'), 'answer_keys', ['question_paper_version_id'], unique=False)
    op.create_index(op.f('ix_answer_keys_status'), 'answer_keys', ['status'], unique=False)
    op.create_table('examinations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('subject_id', GUID(), nullable=False),
    sa.Column('question_paper_id', GUID(), nullable=True),
    sa.Column('question_paper_version_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('examination_type', sa.String(length=50), nullable=False),
    sa.Column('exam_date', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ONGOING', 'COMPLETED', 'EVALUATION', 'RESULT_PUBLISHED', 'ARCHIVED', name='examstatusenum'), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_version_id'], ['question_paper_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examinations_question_paper_id'), 'examinations', ['question_paper_id'], unique=False)
    op.create_index(op.f('ix_examinations_question_paper_version_id'), 'examinations', ['question_paper_version_id'], unique=False)
    op.create_index(op.f('ix_examinations_status'), 'examinations', ['status'], unique=False)
    op.create_index(op.f('ix_examinations_subject_id'), 'examinations', ['subject_id'], unique=False)
    op.create_table('question_bank_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_bank_id', GUID(), nullable=False),
    sa.Column('question_id', GUID(), nullable=False),
    sa.Column('added_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_bank_id', 'question_id', name='uq_bank_question_unique')
    )
    op.create_index(op.f('ix_question_bank_items_question_bank_id'), 'question_bank_items', ['question_bank_id'], unique=False)
    op.create_index(op.f('ix_question_bank_items_question_id'), 'question_bank_items', ['question_id'], unique=False)
    op.create_table('question_paper_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_paper_version_id', GUID(), nullable=False),
    sa.Column('question_id', GUID(), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('question_number', sa.String(length=20), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('question_text_snapshot', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_version_id'], ['question_paper_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_paper_version_id', 'question_number', name='uq_paper_version_qnumber')
    )
    op.create_index(op.f('ix_question_paper_items_question_id'), 'question_paper_items', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_paper_items_question_paper_version_id'), 'question_paper_items', ['question_paper_version_id'], unique=False)
    op.create_table('question_versions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_id', GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevelenum'), nullable=False),
    sa.Column('bloom_level', sa.Enum('REMEMBER', 'UNDERSTAND', 'APPLY', 'ANALYZE', 'EVALUATE', 'CREATE', name='bloomlevelenum'), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('changed_by', GUID(), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version_number', name='uq_question_version_number')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_table('answer_key_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('answer_key_id', GUID(), nullable=False),
    sa.Column('question_paper_item_id', GUID(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=True),
    sa.Column('acceptable_answers', sa.JSON(), nullable=True),
    sa.Column('marking_notes', sa.Text(), nullable=True),
    sa.Column('maximum_marks', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_key_id'], ['answer_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_paper_item_id'], ['question_paper_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_key_id', 'question_paper_item_id', name='uq_answer_key_qitem_unique')
    )
    op.create_index(op.f('ix_answer_key_items_answer_key_id'), 'answer_key_items', ['answer_key_id'], unique=False)
    op.create_index(op.f('ix_answer_key_items_question_paper_item_id'), 'answer_key_items', ['question_paper_item_id'], unique=False)
    op.create_table('answer_papers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('student_id', GUID(), nullable=False),
    sa.Column('file_asset_id', GUID(), nullable=True),
    sa.Column('submission_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'OCR_COMPLETED', 'EVALUATION_PENDING', 'EVALUATED', 'UNDER_REVIEW', 'FINALIZED', 'ERROR', name='answerpaperstatusenum'), nullable=False),
    sa.Column('uploaded_at', sa.String(length=30), nullable=True),
    sa.Column('processed_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'student_id', 'submission_number', name='uq_answer_paper_student_exam_sub')
    )
    op.create_index(op.f('ix_answer_papers_examination_id'), 'answer_papers', ['examination_id'], unique=False)
    op.create_index(op.f('ix_answer_papers_file_asset_id'), 'answer_papers', ['file_asset_id'], unique=False)
    op.create_index(op.f('ix_answer_papers_status'), 'answer_papers', ['status'], unique=False)
    op.create_index(op.f('ix_answer_papers_student_id'), 'answer_papers', ['student_id'], unique=False)
    op.create_table('examination_analytics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('average_marks', sa.Float(), nullable=False),
    sa.Column('median_marks', sa.Float(), nullable=False),
    sa.Column('highest_marks', sa.Float(), nullable=False),
    sa.Column('lowest_marks', sa.Float(), nullable=False),
    sa.Column('pass_percentage', sa.Float(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('evaluated_students', sa.Integer(), nullable=False),
    sa.Column('question_statistics', sa.JSON(), nullable=True),
    sa.Column('unit_statistics', sa.JSON(), nullable=True),
    sa.Column('difficulty_statistics', sa.JSON(), nullable=True),
    sa.Column('bloom_statistics', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examination_analytics_examination_id'), 'examination_analytics', ['examination_id'], unique=False)
    op.create_table('examination_students',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('student_id', GUID(), nullable=False),
    sa.Column('registration_number_snapshot', sa.String(length=50), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'DEBARRED', name='attendancestatusenum'), nullable=False),
    sa.Column('final_marks', sa.Float(), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'student_id', name='uq_exam_student_unique')
    )
    op.create_index(op.f('ix_examination_students_examination_id'), 'examination_students', ['examination_id'], unique=False)
    op.create_index(op.f('ix_examination_students_student_id'), 'examination_students', ['student_id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('question_id', GUID(), nullable=True),
    sa.Column('question_paper_item_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_paper_item_id'], ['question_paper_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_question_id'), 'rubrics', ['question_id'], unique=False)
    op.create_index(op.f('ix_rubrics_question_paper_item_id'), 'rubrics', ['question_paper_item_id'], unique=False)
    op.create_table('student_performances',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('student_id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('topic_statistics', sa.JSON(), nullable=True),
    sa.Column('unit_statistics', sa.JSON(), nullable=True),
    sa.Column('difficulty_statistics', sa.JSON(), nullable=True),
    sa.Column('strong_topics', sa.JSON(), nullable=True),
    sa.Column('weak_topics', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_performances_examination_id'), 'student_performances', ['examination_id'], unique=False)
    op.create_index(op.f('ix_student_performances_student_id'), 'student_performances', ['student_id'], unique=False)
    op.create_table('answer_pages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('answer_paper_id', GUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('file_asset_id', GUID(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_paper_id'], ['answer_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_asset_id'], ['file_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_paper_id', 'page_number', name='uq_answer_page_number')
    )
    op.create_index(op.f('ix_answer_pages_answer_paper_id'), 'answer_pages', ['answer_paper_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('answer_paper_id', GUID(), nullable=False),
    sa.Column('student_id', GUID(), nullable=False),
    sa.Column('evaluator_type', sa.Enum('AI', 'FACULTY', 'HYBRID', name='evaluatortypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='evaluationstatusenum'), nullable=False),
    sa.Column('total_ai_marks', sa.Float(), nullable=True),
    sa.Column('total_final_marks', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.String(length=30), nullable=True),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_paper_id'], ['answer_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_answer_paper_id'), 'evaluations', ['answer_paper_id'], unique=False)
    op.create_index(op.f('ix_evaluations_examination_id'), 'evaluations', ['examination_id'], unique=False)
    op.create_index(op.f('ix_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_index(op.f('ix_evaluations_student_id'), 'evaluations', ['student_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('rubric_id', GUID(), nullable=False),
    sa.Column('criterion', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_criteria_rubric_id'), 'rubric_criteria', ['rubric_id'], unique=False)
    op.create_table('extracted_answers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('answer_paper_id', GUID(), nullable=False),
    sa.Column('question_paper_item_id', GUID(), nullable=True),
    sa.Column('answer_page_id', GUID(), nullable=True),
    sa.Column('question_number', sa.String(length=20), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.Enum('OCR', 'MANUAL', 'HYBRID', name='extractionmethodenum'), nullable=False),
    sa.Column('manually_corrected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_page_id'], ['answer_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['answer_paper_id'], ['answer_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_paper_item_id'], ['question_paper_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_answers_answer_paper_id'), 'extracted_answers', ['answer_paper_id'], unique=False)
    op.create_index(op.f('ix_extracted_answers_question_paper_item_id'), 'extracted_answers', ['question_paper_item_id'], unique=False)
    op.create_table('answer_similarities',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('source_answer_id', GUID(), nullable=False),
    sa.Column('target_answer_id', GUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_answer_id'], ['extracted_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_answer_id'], ['extracted_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_similarities_source_answer_id'), 'answer_similarities', ['source_answer_id'], unique=False)
    op.create_index(op.f('ix_answer_similarities_target_answer_id'), 'answer_similarities', ['target_answer_id'], unique=False)
    op.create_table('evaluation_items',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('evaluation_id', GUID(), nullable=False),
    sa.Column('question_paper_item_id', GUID(), nullable=False),
    sa.Column('extracted_answer_id', GUID(), nullable=True),
    sa.Column('maximum_marks', sa.Float(), nullable=False),
    sa.Column('keyword_score', sa.Float(), nullable=True),
    sa.Column('concept_score', sa.Float(), nullable=True),
    sa.Column('semantic_score', sa.Float(), nullable=True),
    sa.Column('pattern_score', sa.Float(), nullable=True),
    sa.Column('rubric_score', sa.Float(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_marks', sa.Float(), nullable=True),
    sa.Column('final_marks', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('matched_keywords', sa.JSON(), nullable=True),
    sa.Column('missing_keywords', sa.JSON(), nullable=True),
    sa.Column('matched_concepts', sa.JSON(), nullable=True),
    sa.Column('missing_concepts', sa.JSON(), nullable=True),
    sa.Column('evaluation_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extracted_answer_id'], ['extracted_answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_item_id'], ['question_paper_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_items_evaluation_id'), 'evaluation_items', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_items_extracted_answer_id'), 'evaluation_items', ['extracted_answer_id'], unique=False)
    op.create_index(op.f('ix_evaluation_items_question_paper_item_id'), 'evaluation_items', ['question_paper_item_id'], unique=False)
    op.create_table('plagiarism_results',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('examination_id', GUID(), nullable=False),
    sa.Column('answer_paper_id', GUID(), nullable=False),
    sa.Column('answer_a_id', GUID(), nullable=True),
    sa.Column('answer_b_id', GUID(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('matching_segments', sa.JSON(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['answer_a_id'], ['extracted_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['answer_b_id'], ['extracted_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['answer_paper_id'], ['answer_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plagiarism_results_answer_paper_id'), 'plagiarism_results', ['answer_paper_id'], unique=False)
    op.create_index(op.f('ix_plagiarism_results_examination_id'), 'plagiarism_results', ['examination_id'], unique=False)
    op.create_table('evaluation_feedbacks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('evaluation_item_id', GUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('CORRECT', 'MISSING_CONCEPT', 'IMPROVEMENT', 'STRUCTURE', 'CONCEPT_GAP', name='feedbacktypeenum'), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_item_id'], ['evaluation_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_feedbacks_evaluation_item_id'), 'evaluation_feedbacks', ['evaluation_item_id'], unique=False)
    op.create_table('faculty_reviews',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('evaluation_id', GUID(), nullable=False),
    sa.Column('evaluation_item_id', GUID(), nullable=True),
    sa.Column('faculty_id', GUID(), nullable=False),
    sa.Column('original_ai_marks', sa.Float(), nullable=True),
    sa.Column('revised_marks', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('APPROVED', 'MODIFIED', 'REJECTED', 'RE_EVALUATED', name='reviewactionenum'), nullable=False),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_item_id'], ['evaluation_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_reviews_evaluation_id'), 'faculty_reviews', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_faculty_reviews_evaluation_item_id'), 'faculty_reviews', ['evaluation_item_id'], unique=False)
    op.create_index(op.f('ix_faculty_reviews_faculty_id'), 'faculty_reviews', ['faculty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_reviews_faculty_id'), table_name='faculty_reviews')
    op.drop_index(op.f('ix_faculty_reviews_evaluation_item_id'), table_name='faculty_reviews')
    op.drop_index(op.f('ix_faculty_reviews_evaluation_id'), table_name='faculty_reviews')
    op.drop_table('faculty_reviews')
    op.drop_index(op.f('ix_evaluation_feedbacks_evaluation_item_id'), table_name='evaluation_feedbacks')
    op.drop_table('evaluation_feedbacks')
    op.drop_index(op.f('ix_plagiarism_results_examination_id'), table_name='plagiarism_results')
    op.drop_index(op.f('ix_plagiarism_results_answer_paper_id'), table_name='plagiarism_results')
    op.drop_table('plagiarism_results')
    op.drop_index(op.f('ix_evaluation_items_question_paper_item_id'), table_name='evaluation_items')
    op.drop_index(op.f('ix_evaluation_items_extracted_answer_id'), table_name='evaluation_items')
    op.drop_index(op.f('ix_evaluation_items_evaluation_id'), table_name='evaluation_items')
    op.drop_table('evaluation_items')
    op.drop_index(op.f('ix_answer_similarities_target_answer_id'), table_name='answer_similarities')
    op.drop_index(op.f('ix_answer_similarities_source_answer_id'), table_name='answer_similarities')
    op.drop_table('answer_similarities')
    op.drop_index(op.f('ix_extracted_answers_question_paper_item_id'), table_name='extracted_answers')
    op.drop_index(op.f('ix_extracted_answers_answer_paper_id'), table_name='extracted_answers')
    op.drop_table('extracted_answers')
    op.drop_index(op.f('ix_rubric_criteria_rubric_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_evaluations_student_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_examination_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_answer_paper_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_answer_pages_answer_paper_id'), table_name='answer_pages')
    op.drop_table('answer_pages')
    op.drop_index(op.f('ix_student_performances_student_id'), table_name='student_performances')
    op.drop_index(op.f('ix_student_performances_examination_id'), table_name='student_performances')
    op.drop_table('student_performances')
    op.drop_index(op.f('ix_rubrics_question_paper_item_id'), table_name='rubrics')
    op.drop_index(op.f('ix_rubrics_question_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_examination_students_student_id'), table_name='examination_students')
    op.drop_index(op.f('ix_examination_students_examination_id'), table_name='examination_students')
    op.drop_table('examination_students')
    op.drop_index(op.f('ix_examination_analytics_examination_id'), table_name='examination_analytics')
    op.drop_table('examination_analytics')
    op.drop_index(op.f('ix_answer_papers_student_id'), table_name='answer_papers')
    op.drop_index(op.f('ix_answer_papers_status'), table_name='answer_papers')
    op.drop_index(op.f('ix_answer_papers_file_asset_id'), table_name='answer_papers')
    op.drop_index(op.f('ix_answer_papers_examination_id'), table_name='answer_papers')
    op.drop_table('answer_papers')
    op.drop_index(op.f('ix_answer_key_items_question_paper_item_id'), table_name='answer_key_items')
    op.drop_index(op.f('ix_answer_key_items_answer_key_id'), table_name='answer_key_items')
    op.drop_table('answer_key_items')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_index(op.f('ix_question_paper_items_question_paper_version_id'), table_name='question_paper_items')
    op.drop_index(op.f('ix_question_paper_items_question_id'), table_name='question_paper_items')
    op.drop_table('question_paper_items')
    op.drop_index(op.f('ix_question_bank_items_question_id'), table_name='question_bank_items')
    op.drop_index(op.f('ix_question_bank_items_question_bank_id'), table_name='question_bank_items')
    op.drop_table('question_bank_items')
    op.drop_index(op.f('ix_examinations_subject_id'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_status'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_question_paper_version_id'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_question_paper_id'), table_name='examinations')
    op.drop_table('examinations')
    op.drop_index(op.f('ix_answer_keys_status'), table_name='answer_keys')
    op.drop_index(op.f('ix_answer_keys_question_paper_version_id'), table_name='answer_keys')
    op.drop_table('answer_keys')
    op.drop_index(op.f('ix_questions_unit_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_learning_outcome_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloom_level'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_paper_versions_question_paper_id'), table_name='question_paper_versions')
    op.drop_table('question_paper_versions')
    op.drop_index(op.f('ix_topics_unit_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_question_papers_subject_id'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_status'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_paper_code'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_blueprint_id'), table_name='question_papers')
    op.drop_table('question_papers')
    op.drop_index(op.f('ix_blueprint_rules_blueprint_id'), table_name='blueprint_rules')
    op.drop_table('blueprint_rules')
    op.drop_index(op.f('ix_units_subject_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_question_banks_subject_id'), table_name='question_banks')
    op.drop_table('question_banks')
    op.drop_index(op.f('ix_learning_outcomes_subject_id'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_index(op.f('ix_blueprints_subject_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_status'), table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_subjects_semester_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_department_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_course_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_academic_year_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_file_assets_file_category'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_registration_number'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_semesters_number'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_academic_years_name'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_is_current'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
